service:
  name: itc-helper

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  environment:
    DYNAMODB_TABLE_ACCESS_TOKEN: ${env:DYNAMODB_TABLE_ACCESS_TOKEN}
    DYNAMODB_TABLE_REFRESH_TOKEN: ${env:DYNAMODB_TABLE_REFRESH_TOKEN}
    DYNAMODB_TABLE_AUTHORIZATION_CODE: ${env:DYNAMODB_TABLE_AUTHORIZATION_CODE}
    DYNAMODB_TABLE_USER: ${env:DYNAMODB_TABLE_USER}
    DYNAMODB_TABLE_SUBJECT: ${env:DYNAMODB_TABLE_SUBJECT}
    DYNAMODB_TABLE_REPORT: ${env:DYNAMODB_TABLE_REPORT}
    KMS_KEY_ID: ${env:KMS_KEY_ID}
    SECRET_KEY: ${env:SECRET_KEY}
    SQS_QUEUE_URL: ${env:SQS_QUEUE_URL}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateTable
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:*'
    - Effect: Allow
      Action:
        - ses:SendMail
      Resource: 'arn:aws:ses:${opt:region, self:provider.region}:*:*'
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: 'arn:aws:ses:${opt:region, self:provider.region}:*:*'
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: 'arn:aws:sqs:${opt:region, self:provider.region}:*:*'

functions:
  backend:
    handler: src/api.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origin: 'https://itc-helper.dguri.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
          cors:
            origin: 'https://itc-helper.dguri.io'
            headers:
              - Cookie
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: true

custom:
  apigwBinary:
    types: #list of mime-types
      - 'multipart/form-data'
      - 'application/x-www-form-urlencoded'
  customDomain:
    domainName: api.itc-helper.dguri.io
    certificateName: api.itc-helper.dguri.io
    createRoute53Record: true
    endpointType: 'regional'
  serverless-offline:
    port: 4000
